name: stack-yaml
version: 0.0.0.0
synopsis: Helper to modify stack-yaml
description: |
  Helper to modify stack-yaml
  .
  @
  stack yaml update-github-deps
  @
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/stack-yaml
category: Development
tested-with: GHC==7.10.3
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
- base >=4.7 && <4.9
- base-compat
- bytestring
- Cabal
- exceptions
- github
- transformers
- lens
- lens-aeson
- optparse-applicative
- packdeps
- http-client
- http-client-tls
- regex-applicative
- regex-applicative-text
- text
- vector
- yaml >=0.8.14

executables:
  stack-yaml:
    main: Main.hs
    other-modules:
      - StackYaml.Normalize
      - StackYaml.Transformations.CopyPackages
      - StackYaml.Transformations.UpdateExtraDeps
      - StackYaml.Transformations.UpdateGithubDeps
    source-dirs: src
